export const requests = {
    'auth-cognito': '**/auth/cognito-pool-settings**',
    'sign-in': '/auth/sign-in',
    'user-me': '/user/me',
    'customer-status': '/customer/status',
    'customer-statistics': '/alert/customer-statistics**',
    'alerts-statistics': '/alert/service-statistics**',
    'protection-scores': '/protection-scores',
    'customer-statistics': '/alert/customer-statistics**',
    'customer-top-statistics': '**/alert/customer-top-statistics**',
    'service-statistics': '**/alert/service-statistics**',
    'alert-search': '**/alert/search**',
    'catalog-items': '/catalog/items',
    'catalog-packages': '/catalog/packages',
    'service-licenses-order': '/service-licenses/order',
    'services': '/services',
    'service-licenses-policies': '/service-licenses/policies',
    'role-search': '/role/search',
    'device-search': '/device/search',
    'user-search': '/user/search',
    'user-remove': '/user/remove',
    'customer-search': '/customer/search',
    'customer-invitations': '/customer-invitations'
}