export const signUpPage = {
    'firstNameField': '[formcontrolname="firstName"]',
    'lastNameField': '[formcontrolname="lastName"]',
    'emailField': '[formcontrolname="email"]',
    'phoneNumberField': '[formcontrolname="phoneNumber"]',
    'personalUrlField': '[formcontrolname="siteUrl"]',
    'companyNameField': '[formcontrolname="companyName"]',
    'taxNumberField': '[formcontrolname="taxNumber"]',
    'numberOfEmployeesField': '[formcontrolname="numberOfUsers"]',
    'companyWebAddressField': '[formcontrolname="companyWebAddress"]',
    'countryDropdown': '[formcontrolname="country"]',
    'stateDropdown': '[formcontrolname="state"]',
    'cityField': '[formcontrolname="city"]',
    'zipField': '[formcontrolname="zip"]',
    'passwordField': '[formcontrolname="password"]',
    'confirmPasswordField': '[formcontrolname="confirmPassword"]',
    'emailCodeField': '[formcontrolname="code"]',
    'btnContinueStep1': '.action-wrapper > .mat-focus-indicator',
    'btnContinueStep2': '#cdk-step-content-0-1 > .step-item > .action-wrapper > .row > :nth-child(2) > .mat-focus-indicator',
    'btnContinueStep3': '#cdk-step-content-0-2 > .step-item > .action-wrapper > .row > :nth-child(2) > .mat-focus-indicator',
    'btnContinueStep4': '#cdk-step-content-0-3 > .step-item > .action-wrapper > .row > :nth-child(2) > .mat-focus-indicator'
}